/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quad_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[9] = {6, 3, 0, 1, 2, 3, 3, 4, 5};
static const casadi_int casadi_s1[12] = {3, 6, 0, 0, 0, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s2[18] = {6, 3, 0, 4, 8, 12, 0, 1, 2, 3, 0, 1, 2, 4, 0, 1, 2, 5};
static const casadi_int casadi_s3[15] = {6, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s4[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s5[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s6[24] = {6, 3, 0, 6, 12, 18, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s8[3] = {0, 0, 0};
static const casadi_int casadi_s9[27] = {6, 6, 0, 3, 6, 9, 12, 15, 18, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};

/* quad_expl_vde_forw:(i0[6],i1[6x6],i2[6x3],i3[3],i4[])->(o0[6],o1[6x6,18nz],o2[6x3,12nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+6, w1, *w2=w+10, *w3=w+46, *w4=w+52, *w5=w+58, *w6=w+64, *w7=w+70, *w8=w+76, *w10=w+82, w11, w12, *w13=w+87, *w14=w+90, *w15=w+102, *w18=w+120, *w19=w+123, *w20=w+132;
  /* #0: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w0);
  /* #1: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #2: @1 = input[3][0] */
  w1 = arg[3] ? arg[3][0] : 0;
  /* #3: output[0][1] = @1 */
  if (res[0]) res[0][3] = w1;
  /* #4: @1 = input[3][1] */
  w1 = arg[3] ? arg[3][1] : 0;
  /* #5: output[0][2] = @1 */
  if (res[0]) res[0][4] = w1;
  /* #6: @1 = input[3][2] */
  w1 = arg[3] ? arg[3][2] : 0;
  /* #7: output[0][3] = @1 */
  if (res[0]) res[0][5] = w1;
  /* #8: @2 = input[1][0] */
  casadi_copy(arg[1], 36, w2);
  /* #9: {@3, @4, @5, @6, @7, @8} = horzsplit(@2) */
  casadi_copy(w2, 6, w3);
  casadi_copy(w2+6, 6, w4);
  casadi_copy(w2+12, 6, w5);
  casadi_copy(w2+18, 6, w6);
  casadi_copy(w2+24, 6, w7);
  casadi_copy(w2+30, 6, w8);
  /* #10: {NULL, @0} = vertsplit(@3) */
  casadi_copy(w3+3, 3, w0);
  /* #11: output[1][0] = @0 */
  casadi_copy(w0, 3, res[1]);
  /* #12: {NULL, @0} = vertsplit(@4) */
  casadi_copy(w4+3, 3, w0);
  /* #13: output[1][1] = @0 */
  if (res[1]) casadi_copy(w0, 3, res[1]+3);
  /* #14: {NULL, @0} = vertsplit(@5) */
  casadi_copy(w5+3, 3, w0);
  /* #15: output[1][2] = @0 */
  if (res[1]) casadi_copy(w0, 3, res[1]+6);
  /* #16: {NULL, @0} = vertsplit(@6) */
  casadi_copy(w6+3, 3, w0);
  /* #17: output[1][3] = @0 */
  if (res[1]) casadi_copy(w0, 3, res[1]+9);
  /* #18: {NULL, @0} = vertsplit(@7) */
  casadi_copy(w7+3, 3, w0);
  /* #19: output[1][4] = @0 */
  if (res[1]) casadi_copy(w0, 3, res[1]+12);
  /* #20: {NULL, @0} = vertsplit(@8) */
  casadi_copy(w8+3, 3, w0);
  /* #21: output[1][5] = @0 */
  if (res[1]) casadi_copy(w0, 3, res[1]+15);
  /* #22: @0 = zeros(3x6,3nz) */
  casadi_clear(w0, 3);
  /* #23: @9 = zeros(3x1,0nz) */
  /* #24: @10 = ones(3x1) */
  casadi_fill(w10, 3, 1.);
  /* #25: {@1, @11, @12} = vertsplit(@10) */
  w1 = w10[0];
  w11 = w10[1];
  w12 = w10[2];
  /* #26: @10 = vertcat(@9, @1, @11, @12) */
  rr=w10;
  *rr++ = w1;
  *rr++ = w11;
  *rr++ = w12;
  /* #27: @13 = @10[:3] */
  for (rr=w13, ss=w10+0; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #28: (@0[:3] = @13) */
  for (rr=w0+0, ss=w13; rr!=w0+3; rr+=1) *rr = *ss++;
  /* #29: @13 = @0' */
  casadi_trans(w0,casadi_s1, w13, casadi_s0, iw);
  /* #30: @14 = project(@13) */
  casadi_project(w13, casadi_s0, w14, casadi_s2, w);
  /* #31: @15 = input[2][0] */
  casadi_copy(arg[2], 18, w15);
  /* #32: {@8, @7, @6} = horzsplit(@15) */
  casadi_copy(w15, 6, w8);
  casadi_copy(w15+6, 6, w7);
  casadi_copy(w15+12, 6, w6);
  /* #33: {NULL, @13} = vertsplit(@8) */
  casadi_copy(w8+3, 3, w13);
  /* #34: @9 = 00 */
  /* #35: @16 = 00 */
  /* #36: @17 = 00 */
  /* #37: @0 = vertcat(@13, @9, @16, @17) */
  rr=w0;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #38: {NULL, @13} = vertsplit(@7) */
  casadi_copy(w7+3, 3, w13);
  /* #39: @9 = 00 */
  /* #40: @16 = 00 */
  /* #41: @17 = 00 */
  /* #42: @10 = vertcat(@13, @9, @16, @17) */
  rr=w10;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #43: {NULL, @13} = vertsplit(@6) */
  casadi_copy(w6+3, 3, w13);
  /* #44: @9 = 00 */
  /* #45: @16 = 00 */
  /* #46: @17 = 00 */
  /* #47: @18 = vertcat(@13, @9, @16, @17) */
  rr=w18;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #48: @19 = horzcat(@0, @10, @18) */
  rr=w19;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  /* #49: @20 = project(@19) */
  casadi_project(w19, casadi_s3, w20, casadi_s2, w);
  /* #50: @14 = (@14+@20) */
  for (i=0, rr=w14, cs=w20; i<12; ++i) (*rr++) += (*cs++);
  /* #51: output[2][0] = @14 */
  casadi_copy(w14, 12, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quad_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quad_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quad_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void quad_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quad_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quad_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real quad_expl_vde_forw_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_expl_vde_forw_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_expl_vde_forw_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s9;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quad_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 4;
  if (sz_w) *sz_w = 144;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
