/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quad_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[11] = {14, 1, 0, 7, 3, 4, 5, 9, 11, 12, 13};

/* quad_expl_vde_adj:(i0[11],i1[11],i2[3],i3[3])->(o0[14x1,7nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+0, *w1=w+11, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 11, w0);
  /* #1: {@1, @2, @3, @4, @5, @6, @7, @8, @9} = vertsplit(@0) */
  casadi_copy(w0, 3, w1);
  w2 = w0[3];
  w3 = w0[4];
  w4 = w0[5];
  w5 = w0[6];
  w6 = w0[7];
  w7 = w0[8];
  w8 = w0[9];
  w9 = w0[10];
  /* #2: output[0][0] = @1 */
  casadi_copy(w1, 3, res[0]);
  /* #3: output[0][1] = @9 */
  if (res[0]) res[0][3] = w9;
  /* #4: @9 = input[2][0] */
  w9 = arg[2] ? arg[2][0] : 0;
  /* #5: @10 = input[2][1] */
  w10 = arg[2] ? arg[2][1] : 0;
  /* #6: @11 = input[2][2] */
  w11 = arg[2] ? arg[2][2] : 0;
  /* #7: @1 = vertcat(@9, @10, @11) */
  rr=w1;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #8: @1 = (@8*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) (*rr++)  = (w8*(*cs++));
  /* #9: @1 = (2.*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #10: {@8, @9, @10} = vertsplit(@1) */
  w8 = w1[0];
  w9 = w1[1];
  w10 = w1[2];
  /* #11: @1 = input[3][0] */
  casadi_copy(arg[3], 3, w1);
  /* #12: @11 = @1[1] */
  for (rr=(&w11), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #13: @12 = (@11*@7) */
  w12  = (w11*w7);
  /* #14: @8 = (@8+@12) */
  w8 += w12;
  /* #15: @12 = @1[2] */
  for (rr=(&w12), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #16: @13 = (@12*@6) */
  w13  = (w12*w6);
  /* #17: @8 = (@8-@13) */
  w8 -= w13;
  /* #18: @8 = (@8+@2) */
  w8 += w2;
  /* #19: output[0][2] = @8 */
  if (res[0]) res[0][4] = w8;
  /* #20: @8 = @1[0] */
  for (rr=(&w8), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #21: @7 = (@8*@7) */
  w7  = (w8*w7);
  /* #22: @9 = (@9-@7) */
  w9 -= w7;
  /* #23: @12 = (@12*@5) */
  w12 *= w5;
  /* #24: @9 = (@9+@12) */
  w9 += w12;
  /* #25: @9 = (@9+@3) */
  w9 += w3;
  /* #26: output[0][3] = @9 */
  if (res[0]) res[0][5] = w9;
  /* #27: @8 = (@8*@6) */
  w8 *= w6;
  /* #28: @10 = (@10+@8) */
  w10 += w8;
  /* #29: @11 = (@11*@5) */
  w11 *= w5;
  /* #30: @10 = (@10-@11) */
  w10 -= w11;
  /* #31: @10 = (@10+@4) */
  w10 += w4;
  /* #32: output[0][4] = @10 */
  if (res[0]) res[0][6] = w10;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quad_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quad_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quad_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void quad_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quad_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quad_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quad_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quad_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 26;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
