/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quad_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

static const casadi_int casadi_s0[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};

/* quad_expl_ode_fun:(i0[11],i1[3],i2[3])->(o0[11]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1, w2, w3, w4, w5, w6, w7;
  /* #0: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w0);
  /* #1: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #2: @1 = input[1][0] */
  w1 = arg[1] ? arg[1][0] : 0;
  /* #3: output[0][1] = @1 */
  if (res[0]) res[0][3] = w1;
  /* #4: @2 = input[1][1] */
  w2 = arg[1] ? arg[1][1] : 0;
  /* #5: output[0][2] = @2 */
  if (res[0]) res[0][4] = w2;
  /* #6: @3 = input[1][2] */
  w3 = arg[1] ? arg[1][2] : 0;
  /* #7: output[0][3] = @3 */
  if (res[0]) res[0][5] = w3;
  /* #8: @0 = input[2][0] */
  casadi_copy(arg[2], 3, w0);
  /* #9: @4 = @0[2] */
  for (rr=(&w4), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #10: @5 = (@2*@4) */
  w5  = (w2*w4);
  /* #11: @6 = @0[1] */
  for (rr=(&w6), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #12: @7 = (@3*@6) */
  w7  = (w3*w6);
  /* #13: @5 = (@5-@7) */
  w5 -= w7;
  /* #14: output[0][4] = @5 */
  if (res[0]) res[0][6] = w5;
  /* #15: @5 = @0[0] */
  for (rr=(&w5), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #16: @7 = (@3*@5) */
  w7  = (w3*w5);
  /* #17: @4 = (@1*@4) */
  w4  = (w1*w4);
  /* #18: @7 = (@7-@4) */
  w7 -= w4;
  /* #19: output[0][5] = @7 */
  if (res[0]) res[0][7] = w7;
  /* #20: @6 = (@1*@6) */
  w6  = (w1*w6);
  /* #21: @5 = (@2*@5) */
  w5  = (w2*w5);
  /* #22: @6 = (@6-@5) */
  w6 -= w5;
  /* #23: output[0][6] = @6 */
  if (res[0]) res[0][8] = w6;
  /* #24: @0 = vertcat(@1, @2, @3) */
  rr=w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  /* #25: @1 = dot(@0, @0) */
  w1 = casadi_dot(3, w0, w0);
  /* #26: output[0][7] = @1 */
  if (res[0]) res[0][9] = w1;
  /* #27: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][9] : 0;
  /* #28: output[0][8] = @1 */
  if (res[0]) res[0][10] = w1;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quad_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quad_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quad_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quad_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quad_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int quad_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quad_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quad_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 10;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
